### ISSUE TITLE
compilation on ubuntu 16.04 lts

### ISSUE THREAD

**Issue by goodthebest** [Pakcoin-project/pakcoinold#3]
How do I compile in ubuntu 16.04 ?

when I run  **pakcoind** I get this error
> error while loading shared libraries: libboost_system.so.1.54.0: cannot open shared object file: No such file or directory

then I tried  **make -f makefile.unix test**
>rpcrawtransaction.cpp:242:77:   required from here
/usr/include/boost/variant/get.hpp:178:5: error: invalid application of ‘sizeof’ to incomplete type ‘boost::STATIC                     _ASSERTION_FAILURE<false>’
     BOOST_STATIC_ASSERT_MSG(
     ^
makefile.unix:186: recipe for target 'obj/rpcrawtransaction.o' failed
make: *** [obj/rpcrawtransaction.o] Error 1

**Comment by drwatson84** [comment]
seems you dont have libbosst dependency, you need to install dependencies first to compile pakcoind
Do
apt-get update
sudo apt-get install libboost1.54-all-dev
sudo apt-get install libdb-dev libdb++-dev
sudo apt-get install libminiupnpc-dev

`rpcrawtransaction.cpp:242:77: required from here
/usr/include/boost/variant/get.hpp:178:5: error: invalid application of ‘sizeof’ to incomplete type ‘boost::STATIC _ASSERTION_FAILURE’
BOOST_STATIC_ASSERT_MSG(
^
makefile.unix:186: recipe for target 'obj/rpcrawtransaction.o' failed
make: *** [obj/rpcrawtransaction.o] Error 1`
rpcrawtransaction.cpp is now updated and you should not see the above error while using latest libboost
https://github.com/Pakcoin-project/pakcoin/commit/29ee136607a16de5a67d1cbdb7fb256148d70e8e
